### ISSUE TITLE
不启动渲染地图程序

### ISSUE THREAD

**Issue by KernSSSS** [pa733/BDSLM#1]
在4点09分发布的最新cpp版本，绝对正确安装以后重启服务器不启动渲染程序，是暂不支持么

**Comment by pa733** [comment]
并不是，0.1版本，以及以后的版本都将unmined渲染程序后台执行。
但是0.1版并没有渲染状态的输出，这将在以后的版本加入，敬请期待。

**Comment by pa733** [comment]
0.2已加入渲染程序状态相关的提示。
我们将在后续版本中加入渲染的进度显示。
尽情期待！
